In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('Coursera.csv')
df.head()

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...
1,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...",Finance business plan persona (user experien...
2,Silicon Thin Film Solar Cells,�cole Polytechnique,Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...
3,Finance for Managers,IESE Business School,Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...
4,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...

In [ ]:
df['Course Rating'].unique()

array(['4.8', '4.1', '4.6', '4.7', '3.3', '4.9', '4.3', 'Not Calibrated',
       '4', '4.4', '3.4', '4.5', '4.2', '5', '3.5', '3.7', '3', '3.6',
       '3.8', '3.9', '2.9', '2.6', '2.8', '2', '3.1', '3.2', '2.5', '2.4',
       '1', '1.9', '2.3'], dtype=object)

In [ ]:

df['Course Rating']=df['Course Rating'].replace(':',' ')
df['Course Rating']=df['Course Rating'].replace(',',' ')

df['Course Description']=df['Course Description'].replace('-',' ')
df['Course Description']=df['Course Description'].replace('.',' ')
df['Course Description']=df['Course Description'].replace(':',' ')
df['Course Description']=df['Course Description'].replace(',',' ')

df['Skills']=df['Skills'].replace('-',' ')
df['Skills']=df['Skills'].replace('.',' ')
df['Skills']=df['Skills'].replace(':',' ')
df['Skills']=df['Skills'].replace(',',' ')
df['Skills']=df['Skills'].replace('(',' ')
df['Skills']=df['Skills'].replace(')',' ')

In [ ]:
df = df[df['Course Rating'] != 'Not Calibrated']
df['Course Rating'] = df['Course Rating'].astype(float)
df

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...
1,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...",Finance business plan persona (user experien...
2,Silicon Thin Film Solar Cells,�cole Polytechnique,Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...
3,Finance for Managers,IESE Business School,Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...
4,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...
...,...,...,...,...,...,...,...
3517,"Capstone: Retrieving, Processing, and Visualiz...",University of Michigan,Beginner,4.6,https://www.coursera.org/learn/python-data-vis...,"In the capstone, students will build a series ...",Databases syntax analysis web Data Visuali...
3518,Patrick Henry: Forgotten Founder,University of Virginia,Intermediate,4.9,https://www.coursera.org/learn/henry,"�Give me liberty, or give me death:� Rememberi...",retirement Causality career history of the ...
3519,Business intelligence and data analytics: Gene...,Macquarie University,Advanced,4.6,https://www.coursera.org/learn/business-intell...,�Megatrends� heavily influence today�s organis...,analytics tableau software Business Intellig...
3520,Rigid Body Dynamics,Korea Advanced Institute of Science and Techno...,Beginner,4.6,https://www.coursera.org/learn/rigid-body-dyna...,"This course teaches dynamics, one of the basic...",Angular Mechanical Design fluid mechanics F...
3521,Architecting with Google Kubernetes Engine: Pr...,Google Cloud,Intermediate,4.7,https://www.coursera.org/learn/deploying-secur...,"In this course, ""Architecting with Google Kube...",bigtable bigquery SQL Google Cloud Platform...

In [ ]:
df.drop('Course URL',axis=1)

,Course Name,University,Difficulty Level,Course Rating,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...
1,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,Beginner,4.8,"By the end of this guided project, you will be...",Finance business plan persona (user experien...
2,Silicon Thin Film Solar Cells,�cole Polytechnique,Advanced,4.1,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...
3,Finance for Managers,IESE Business School,Intermediate,4.8,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...
4,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,Beginner,4.6,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...
...,...,...,...,...,...,...
3517,"Capstone: Retrieving, Processing, and Visualiz...",University of Michigan,Beginner,4.6,"In the capstone, students will build a series ...",Databases syntax analysis web Data Visuali...
3518,Patrick Henry: Forgotten Founder,University of Virginia,Intermediate,4.9,"�Give me liberty, or give me death:� Rememberi...",retirement Causality career history of the ...
3519,Business intelligence and data analytics: Gene...,Macquarie University,Advanced,4.6,�Megatrends� heavily influence today�s organis...,analytics tableau software Business Intellig...
3520,Rigid Body Dynamics,Korea Advanced Institute of Science and Techno...,Beginner,4.6,"This course teaches dynamics, one of the basic...",Angular Mechanical Design fluid mechanics F...
3521,Architecting with Google Kubernetes Engine: Pr...,Google Cloud,Intermediate,4.7,"In this course, ""Architecting with Google Kube...",bigtable bigquery SQL Google Cloud Platform...

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer


tfidf = TfidfVectorizer(stop_words='english')

df['Course Description'] = df['Course Description'].fillna('')


tfidf_matrix = tfidf.fit_transform(df['Course Description'])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(tfidf_matrix)

In [ ]:
similarity

array([[1.00000000e+00, 3.11459663e-02, 1.96387593e-02, ...,
        3.16339806e-02, 3.35736348e-02, 1.95034714e-02],
       [3.11459663e-02, 1.00000000e+00, 8.64009706e-03, ...,
        3.13084434e-02, 4.87956408e-03, 4.55297666e-02],
       [1.96387593e-02, 8.64009706e-03, 1.00000000e+00, ...,
        3.48581101e-03, 1.65354788e-02, 6.35537130e-03],
       ...,
       [3.16339806e-02, 3.13084434e-02, 3.48581101e-03, ...,
        1.00000000e+00, 5.08935671e-04, 6.69887848e-03],
       [3.35736348e-02, 4.87956408e-03, 1.65354788e-02, ...,
        5.08935671e-04, 1.00000000e+00, 1.14188876e-03],
       [1.95034714e-02, 4.55297666e-02, 6.35537130e-03, ...,
        6.69887848e-03, 1.14188876e-03, 1.00000000e+00]])

In [ ]:
indices = pd.Series(df.index, index=df['Course Name']).drop_duplicates()

In [ ]:
def get_recommendations(title, cosine_sim=similarity):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:6]
    courses = [i[0] for i in sim_scores]

    return df['Course Name'].iloc[courses]

In [ ]:
get_recommendations('Finance for Managers')

1839    Fundamentals of financial and management accou...
1891          Accounting and Finance for IT professionals
1985                  Introduction to Finance: The Basics
419                    Finance for Non-Financial Managers
1164                         Corporate Finance Essentials
Name: Course Name, dtype: object

In [ ]:
get_recommendations('Silicon Thin Film Solar Cells')

2854               Physics of silicon solar cells
438                   Introduction to solar cells
2144    Organic Solar Cells - Theory and Practice
742                           Solar Energy Basics
1041                    Photovoltaic solar energy
Name: Course Name, dtype: object

In [ ]:
import pickle

In [ ]:
pickle.dump(similarity,open('sim.pkl','wb'))

In [ ]:
pickle.dump(df,open('courses.pkl','wb'))